apiVersion: v1
kind: Pod
metadata:
  name: milvus-cpu-build-env
  labels:
    app: milvus
    componet: cpu-build-env
spec:
  containers:
  - name: milvus-cpu-build-env
    image: registry.zilliz.com/milvus/milvus-cpu-build-env:v0.9.0-centos7
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: OS_NAME
      value: "centos7"
    - name: BUILD_ENV_IMAGE_ID
      value: "f2386d84d312e42891c8c70219b12fde014c21fbdbc0e59bede7e7609b1ba58b"
    command:
    - cat
    tty: true
    resources:
      limits:
        memory: "14Gi"
        cpu: "6.0"
      requests:
        memory: "8Gi"
        cpu: "4.0"
  - name: milvus-mysql
    image: mysql:5.6
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: 123456
    ports:
    - containerPort: 3306
      name: mysql
    resources:
      limits:
        memory: "500Mi"
        cpu: "0.5"
      requests:
        memory: "200Mi"
        cpu: "0.2"
  tolerations:
  - key: dedicated
    operator: Equal
    value: milvus
    effect: NoSchedule
