kind: Service
apiVersion: v1
metadata:
  name: mishards-wo-servers
  namespace: mishards
spec:
  type: ClusterIP
  selector:
    app: mishards
    tier: wo-servers
  ports:
  - protocol: TCP
    port: 19530
    targetPort: 19530

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mishards-wo-servers
  namespace: mishards
spec:
  selector:
    matchLabels:
      app: mishards
      tier: wo-servers
  replicas: 1
  template:
    metadata:
      labels:
        app: mishards
        tier: wo-servers
    spec:
      containers:
      - name: mishards-wo-server
        image: milvusdb/milvus:0.8.0-gpu-d041520-464400
        imagePullPolicy: Always
        ports:
          - containerPort: 19530
        resources:
          limits:
            memory: "4Gi"
            cpu: "2.0"
          requests:
            memory: "4Gi"
        volumeMounts:
        - name: mishards-db-disk
          mountPath: /var/milvus
          subPath: dbdata
        - name: mishards-woserver-configmap
          mountPath: /var/lib/milvus/conf/server_config.yaml
          subPath: config.yml
        - name: mishards-woserver-configmap
          mountPath: /var/lib/milvus/conf/log_config.conf
          subPath: log.conf
        - name: mishards-log-disk
          mountPath: /var/lib/milvus/logs
          subPath: wslog
      # imagePullSecrets:
        # - name: regcred
      # tolerations:
      #   - key: "worker"
      #     operator: "Equal"
      #     value: "performance"
      #     effect: "NoSchedule"
      volumes:
      - name: mishards-woserver-configmap
        configMap:
            name: mishards-woserver-configmap
      - name: mishards-db-disk
        persistentVolumeClaim:
            claimName: mishards-db-disk
      - name: mishards-log-disk
        persistentVolumeClaim:
            claimName: mishards-log-disk
